### ISSUE TITLE
dragonブランチを生やしていただきたい

### ISSUE THREAD

**Issue by chibi314** [tongtybj/d_board#24]
@tongtybj 

そちらのリモートにもdragonブランチがあったほうがいいと思うのでmasterからdragonブランチを生やしていただきたく思います．そこにとりあえずPRを送ります．
neuronのほうも同じで．

**Comment by tongtybj** [comment]
両方作ったよ。
d_boardの方はここ数日、masterブランチにちょくちょくコミットしてたので、もしかして、rebaseして手動で修正しないといけないかも。

あと、neuronのレポジトリ名が"hydrus"になっていることに改めて気づいて、そのうち、この２つのレポジトリを合併して、 その下にd_boardとneuronをディレクトリ分けて管理しようとおもう。 どうかな

**Comment by chibi314** [comment]
#26 にてマージ　衝突解決もした

d_boardとneuronは通信仕様のバージョンが一致していないと動作しないのでそうするべきだと思います．
