### ISSUE TITLE
レポジトリの統合

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/d_board#30]
@chibi314 
d_boardとhydrusを統合するという件だけど、
統合するに際して、注意事項はないでしょうか。

**Comment by chibi314** [comment]
今それぞれのレポジトリにmaster(hydrus用)とdragon(dragon用)があるので，どちらかをサブモジュールとしてではなく普通に入れてしまうとこれが失われてしまうのが問題です．
10月入ったらまず最初にdragonをmasterにマージしてhydrus，dragonもしくは新halo全てmasterで動くようにしたいと思っているのでそれが完了したら統合でいいでしょうか．

そのほかの10月アップデートも同時にやりたいと思います．
理想的にはneuron側はID以外の変更はないようにしたいと思ってます．

**Comment by chibi314** [comment]
一応全部作り終わったつもりなので，統合しても大丈夫です．

**Comment by tongtybj** [comment]
https://github.com/tongtybj/aerial_robot/pull/109
で雛形はできた.
