### ISSUE TITLE
他にアップグレードしたいこと

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/d_board#33]
@chibi314 

他に改善したことがあれば、ここに書きましょう。

1. hydrus/ haloのdynamixel 2.0対応

**Comment by chibi314** [comment]
Neuronで書き換えるのはIDのみにしたい．
起動時にNeuronからサーボにpingすれば何個あるかわかるからサーボが何個あるかとかはいちいち書き換えなくていいはず．何番目のサーボがどの役割にあたるのかというのはPC側が知っていればよい．

今はIDのほかにサーボの個数，ゲイン，速度を変えるようにしているけど，これらもSpinalから最初に送るようにすれば設定できる．

**Comment by tongtybj** [comment]
@chibi314 

#43 (旧 #37)で全部できたよね。

**Comment by chibi314** [comment]
できています．
