### ISSUE TITLE
初期化時に全部のNeuronが登録されない現象

### ISSUE THREAD

**Issue by chibi314** [tongtybj/d_board#46]
初期化時にSpinalがNeuronの列挙を行い全てのNeuronを登録するが，時々（確率は低い）あるはずのNeuronが出てこないことがある．

原因はいろいろ考えられるが，初期化が遅くなるがとりあえずDelayを上げて様子を見てみる．また，PCかSpinalでモデルと実機でリンク数，サーボ数に違いがないかチェックする機構が絶対に必要．

**Comment by tongtybj** [comment]
>> また，PCかSpinalでモデルと実機でリンク数，サーボ数に違いがないかチェックする機構が絶対に必要．

https://github.com/tongtybj/d_board/blob/master/Jsk_Lib/flight_control/attitude/attitude_control.cpp#L615-L663
の２つの関数はSpineとrosserial両方から呼ばれており、一致しているかどうかの確認がなされている。
一致していない場合は, ```motor_number_ = 0```になり、motor armingができなくなる。
