### ISSUE TITLE
std::vectorの必要性

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/d_board#5]
@chibi314

現在はlink数に関してはstd::arrayを使っているで6に固定していて、CAN::SLAVE_NUMも6に固定しているから、リンク数を変えるといろいろ面倒な調整が生じる
1.SERVO_NUM
[コミット0d98cdf](https://github.com/tongtybj/d_board/commit/0d98cdf8113e6950ce7a94ccb1d57544e2306dea)を参照. 6に固定されているCAN::SLAVE_NUMは使えない。

2. motor_number_
[コミットfba3590](https://github.com/tongtybj/d_board/commit/fba359003d2458b6af63bd6602e70bf7798d5f64) を参照. SERVO_NUMと同じ理由

3.  [IMU_WEIGHTS](https://github.com/tongtybj/d_board/blob/a9d7127a9dbdc9a268f95cecc3e51d4f9e8025e8/Hydrus_Lib/Spine/spine.cpp#L22-L29)
いまは, quad, hexで手動で切り替えている。

**対策**
CAN::SLAVE_NUMを可変にして、NUERONに関係するデバイスの[instance](std::array<CANMotor, CAN::SLAVE_NUM> can_motor_)をstd::vectorにすること

**Comment by chibi314** [comment]
対応したはず．
