### ISSUE TITLE
TrueStudio on Linux

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/d_board#51]
@chibi314  
以前から議題になっていたLinux上でのTrueStudioについてですが、
前のバージョン(8.0.0)だと、Flashmemoryへのパラメータの書き込みがうまく行かなかった問題があっただけど、
今回rosserialの整理のついでに、最新のバージョン(8.1.0)を試したみたところ、この問題が解決されたことが実機で確認出来ました。あと、spinalとneuronの両方をLinuxのTrueStudioでコードを焼きなおして、hydrusで変形飛行し、安定な飛行が確認出来ました。

なので、今後はLinuxでTrueStudioを使っても問題ないと判断できるとは思います。

使い方: https://atollic.com/resources/download/ からLinuxを選んでください。インストール方法はダウンロードページに書かれています。個人的には、$PATHにいれるととても便利、 `$Truestudio .project`で直接開けます。

ただし、Ubuntuの場合16.04であることが必須です(T450もそろそろ更新しないと)。

あと、  STM32CubeMXもLinuxに対応しているが判明しました。こちらは来年の３月の第二回大型アップデートの時に、stm32F7のファームウェア(今は2015版の1.3.1)のアップデートと同時に試したいと思います。

https://github.com/tongtybj/d_board/wiki　も少し参考になるかも。

**Comment by chibi314** [comment]
メモ C++プロジェクトへの変更のやり方
http://gsmcustomeffects.hatenablog.com/entry/2017/08/24/011158
